demoweb/Controllers/CategoriesController.cs
using demoweb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace demoweb.Controllers
{
    public class CategoriesController : Controller
    {  
            DBSportStoreEntities database = new DBSportStoreEntities();
            // GET: Categories
            public ActionResult Index()
            {
                var categories = database.Categories.ToList();
                return View(categories);
            }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Category category)
        {
            try
            {
                database.Categories.Add(category);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("loi rui :>");
            }
        }
        public ActionResult Details(int id)
        {
            var category = database.Categories.Where(c => c.Id == id).FirstOrDefault();
            return View(category);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var category = database.Categories.Where(c => c.Id ==
            id).FirstOrDefault();
            return View(category);
        }
        [HttpPost]
        public ActionResult Edit(int id, Category category)
        {
            database.Entry(category).State =
            System.Data.Entity.EntityState.Modified;
            database.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new
                HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var category = database.Categories.Where(c => c.Id ==
            id).FirstOrDefault();
            if (category == null)

            {
                return HttpNotFound();
            }
            return View(category);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var category = database.Categories.Where(c => c.Id ==
                id).FirstOrDefault();
                database.Categories.Remove(category);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Không xóa được do có liên quan đến bảng khác");
            }
        }
        public PartialViewResult CategoryPartial()
        {
            var cateList = database.Categories.ToList();
            return PartialView(cateList);
        }
    }
}

demoweb/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using demoweb.Models;
using System.IO;
using EntityState = System.Data.Entity.EntityState;
using PagedList;

namespace demoweb.Controllers
{
    public class ProductsController : Controller
    {
        private DBSportStoreEntities db = new DBSportStoreEntities();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category1);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include ="ProductID,NamePro,DecriptionPro,Category,Price,ImagePro")] Product product,HttpPostedFileBase ImagePro)
        {
            if (ModelState.IsValid)
            {
                if (ImagePro != null)
                {
                    //Lấy tên file của hình được up lên

                    var fileName = Path.GetFileName(ImagePro.FileName);

                    //Tạo đường dẫn tới file

                    var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    //Lưu tên

                    product.ImagePro = fileName;
                    //Save vào Images Folder
                    ImagePro.SaveAs(path);

                }
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate",
            product.Category);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate", product.Category);
            return View(product);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include ="ProductID,NamePro,DecriptionPro,Category,Price,ImagePro")] Product product,HttpPostedFileBase ImagePro)
        {
            if (ModelState.IsValid)
            {
                var productDB = db.Products.FirstOrDefault(p => p.ProductID ==
                product.ProductID);
                if (productDB != null)
                {
                    productDB.NamePro = product.NamePro;
                    productDB.DecriptionPro = product.DecriptionPro;
                    productDB.Price = product.Price;
                    if (ImagePro != null)
                    {
                        //Lấy tên file của hình được up lên
                        var fileName = Path.GetFileName(ImagePro.FileName);
                        //Tạo đường dẫn tới file
                        var path = Path.Combine(Server.MapPath("~/Images"),fileName);
                        //Lưu tên
                        productDB.ImagePro = fileName;
                        //Save vào Images Folder
                        ImagePro.SaveAs(path);
                    }
                    productDB.Category = product.Category;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate",
            product.Category);
            return View(product);
        }
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        // public ActionResult
        // GET: Products
        public ActionResult ProductList(int? page, string category, string SearchString, double min = double.MinValue, double max = double.MaxValue)
        { // Tạo Products và có tham chiếu đến Category
            var products = db.Products.Include(p => p.Category1);
            // Tìm kiếm chuỗi truy vấn theo category
            if (category == null)
            {
                products = db.Products.OrderByDescending(x => x.NamePro);
            }
            else
            {
                products = db.Products.OrderByDescending(x => x.Category).Where(x => x.Category == category);

            }
            //Tìm kiếm chuỗi truy vấn theo NamePro, nếu chuỗi truy vấn SearchString khác rỗng, null
            if (!String.IsNullOrEmpty(SearchString))
            {
                products = products.Where(s => s.NamePro.Contains(SearchString));
            }
            // Tìm kiếm chuỗi truy vấn theo đơn giá
            if (min >= 0 && max > 0)
            {
                products = db.Products.OrderByDescending(x => x.Price).Where(p => (double)p.Price >= min && (double)p.Price <= max);
            }

            // Khai báo mỗi trang 4 sản phẩm
            int pageSize = 6;
            // Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);
            // Nếu page = null thì đặt lại page là 1.
            if (page == null) page = 1;
            // Trả về các product được phân trang theo kích thước và số trang.
            return View(products.ToPagedList(pageNumber, pageSize));
            ViewBag.Cate = category;
            ViewBag.Search = SearchString;

        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

demoweb/Views/Shared/CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/mystyle.css" />
    <link rel="stylesheet" href="~/Fonts/themify-icons/themify-icons.css" />
    <link href="~/Scripts/script.js" rel="stylesheet" />
    <script src="~/Scripts/JavaScriptlinedown.js"></script>
    <script src="https://kit.fontawesome.com/5026e71056.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="div-top">
        <ul id="nav" style="padding-left: 0;display: block;">
            <li id="top-logo">
                <img src="~/Images/logo-removebg-preview.png" alt="logo" class="logo" />

            <li>
            <li>
                <a href="/Home/Trangchu">Trang Chủ</a>
            </li>
            <li>
                <a href="/Home/Index">Giới Thiệu</a>
            </li>
            <li>
                <a href="/Home/CuaHang">Cửa Hàng</a>
            </li>
            <li>
                <a href="">Nhiều Hơn</a>
                <ul class="subnav">
                    <li>
                        <a href="">content</a>
                    </li>
                    <li>
                        <a href="">content</a>
                    </li>
                    <li>
                        <a href="">content</a>
                    </li>
                </ul>
            </li>
            @* <li>
            <div class="wrap">
                <form action="" class="search" method="post">
                    <input type="text" class="searchTerm" placeholder="Bạn muốn tìm gì?">
                    <button type="submit" class="searchButton">
                        Submit
                    </button>
                </form>
            </div>
        </li>*@

            <ul class="nav2" style="float:right;display:flex">
                <div class="navlogin">
                    <a class="ti-github">
                        @if (Session["TaiKhoan"] != null)
                        {
                            @Session["TaiKhoan"]

                        }
                    </a>
                    <ul class="navlog" style=" padding: 20px;">
                        <li>
                            <a href="/Users/Logout">
                                Logout
                            </a>
                        </li>
                    </ul>


                </div>
                <li>
                    <div class="search-btn" style="padding: 0;">
                        @Html.Action("CartPartial", "Cart")
                    </div>
                </li>

            </ul>

            <div class="order-sidebar sidebar-right">
                @RenderBody()
            </div>
            <footer class="footer" style="background-color: #333" ;>
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">

                            <div class="row">
                                <div class="col-6">
                                    <img src="~/Images/logo-removebg-preview.png" width="90px" style="padding-top: 25px;" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4" style="color:gold">
                            <h5 class="text-md-right" style="padding-top: 50px" ">© BOBATEA. All rights reserved.</h5>

                        </div>
                        <div class="col-md-4" style="padding: 50px;">
                            <a href="" class="item-link" style=" padding: 20px;font-size:30px;">

                                <i class="fa-brands fa-facebook"></i>
                            </a>
                            <a href="" class="item-link" style=" padding: 20px;font-size:30px;">
                                <i class="fa-brands fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </footer>
</body>
</html>

demoweb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/mystyle.css" />
    <link rel="stylesheet" href="~/Fonts/themify-icons/themify-icons.css" />
    <link href="~/Scripts/script.js" rel="stylesheet" />
    <script src="~/Scripts/JavaScriptlinedown.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/5026e71056.js" crossorigin="anonymous"></script>


</head>
<body>
    <div id="div-top">
        <ul id="nav">
            <li id="top-logo">
                <img src="~/Images/logo-removebg-preview.png" alt="logo" class="logo" />

            <li>
            <li>
                <a href="/Home/Trangchu">Trang Chủ</a>
            </li>
            <li>
                <a href="/Home/Index">Giới Thiệu</a>
            </li>
            <li>
                <a href="/Home/CuaHang">Cửa Hàng</a>
            </li>
            <li>
                <a href="#">Nhiều Hơn</a>
                <ul class="subnav">
                    <li>
                        <a href="">content</a>
                    </li>
                    <li>
                        <a href="">content</a>
                    </li>
                    <li>
                        <a href="">content</a>
                    </li>
                </ul>
            </li>
            @* <li>
                <div class="wrap">
                    <form action="" class="search" method="post">
                        <input type="text" class="searchTerm" placeholder="Bạn muốn tìm gì?">
                        <button type="submit" class="searchButton">
                            Submit
                        </button>
                    </form>
                </div>
            </li>*@
        </ul>

        @if (Session["TaiKhoan"] != null)
        {<a class="ti-github">
              @Session["TaiKhoan"]
           </a>
         }

           
          else
        {
            <a href = "/Users/Login" class="ti-github">
              ĐĂNG NHẬP
             </a>}
    </div>
    <div id="bodi">
        <div class="sizeslide">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="https://tocotocotea.com/wp-content/uploads/2022/06/Slide_banner-1-1.jpg" class="d-block w-100" alt="...">
                    </div>

                    <div class="item">
                        <img src="https://tocotocotea.com/wp-content/uploads/2022/06/Slide_banner-2.jpg" class="d-block w-100" alt="...">
                    </div>

                    <div class="item">
                        <img src="https://tocotocotea.com/wp-content/uploads/2022/06/Slide_banner-3.jpg" class="d-block w-100" alt="...">
                    </div>
                </div>

                <!-- Left and right controls -->
                <a style="opacity:-12" class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a style="opacity:-12" class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>

    </div>
    <div id="div-main">
        <div id="div-right">
            @RenderBody()
        </div>
    </div>
    <div-main-content>
        <iframe width="100%" height="400px" src="https://www.youtube.com/embed/jDXYpGZOSiE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div-main-content>
    <footer class="footer" style="background-color: #333" ;>
        <div class="container">
            <div class="row">
                <div class="col-md-4">

                    <div class="row">
                        <div class="col-6">
                            <img src="~/Images/logo-removebg-preview.png" width="90px" style="padding-top: 25px;" />
                        </div>
                    </div>
                </div>
                <div class="col-md-4" style="color:gold">
                    <h5 class="text-md-right" style="padding-top: 50px" ">© BOBATEA. All rights reserved.</h5>

                </div>
                <div class="col-md-4" style="padding: 50px;">
                    <a href="" class="item-link" style=" padding: 20px;font-size:30px;">

                        <i class="fa-brands fa-facebook"></i>
                    </a>
                    <a href="" class="item-link" style=" padding: 20px;font-size:30px;">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>

    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>




</body>
</html>

demoweb/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/mystyle.css" />
    <link rel="stylesheet" href="~/Fonts/themify-icons/themify-icons.css" />
    <link href="~/Scripts/script.js" rel="stylesheet" />
    <script src="~/Scripts/JavaScriptlinedown.js"></script>
    <script src="https://kit.fontawesome.com/5026e71056.js" crossorigin="anonymous"></script>
    <style>
        .login form {
        }
    </style>
</head>

<body>

   <div>
       @RenderBody()
   </div>
</body>
</html>

demoweb/Views/Shared/_MasterLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/mystyle.css" />
    <link rel="stylesheet" href="~/Fonts/themify-icons/themify-icons.css" />
    <link href="~/Scripts/script.js" rel="stylesheet" />
    <script src="~/Scripts/JavaScriptlinedown.js"></script>
    <script src="https://kit.fontawesome.com/5026e71056.js" crossorigin="anonymous"></script>

</head>
<body>
    <div id="div-top">
        <ul id="nav">
            <li id="top-logo">
                <img src="~/Images/logo-removebg-preview.png" alt="logo" class="logo" />

            <li>
            <li>
                <a href="/Home/Trangchu">Trang Chủ</a>
            </li>
            <li>
                <a href="/Home/Index">Giới Thiệu</a>
            </li>
            <li>
                <a href="/Home/CuaHang">Cửa Hàng</a>
            </li>
            <li>
                <a href="">Nhiều Hơn</a>
                <ul class="subnav">
                    <li>
                        <a href="">content</a>
                    </li>
                    <li>
                        <a href="">content</a>
                    </li>
                    <li>
                        <a href="">content</a>
                    </li>
                </ul>
            </li>
            @* <li>
            <div class="wrap">
                <form action="" class="search" method="post">
                    <input type="text" class="searchTerm" placeholder="Bạn muốn tìm gì?">
                    <button type="submit" class="searchButton">
                        Submit
                    </button>
                </form>
            </div>
        </li>*@
            <ul class="nav2" style="float:right;display:flex">
                <div class="navlogin">
                    <a class="ti-github">
                        @if (Session["TaiKhoan"] != null)
                        {
                            @Session["TaiKhoan"]

                        }
                    </a>
                    <ul class="navlog" style=" padding: 20px;">
                        <li>
                            <a href="/Users/Logout">
                                Logout
                            </a>
                        </li>
                    </ul>


                </div>
                <li>
                    <div class="search-btn" style="padding: 0;">
                        @Html.Action("CartPartial", "Cart")
                    </div>
                </li>

            </ul>
</div>

    <div class="order-sidebar sidebar-right">
        @RenderBody()
    </div>

   
    <footer class="footer" style="background-color: #333" ;>
        <div class="container">
            <div class="row">
                <div class="col-md-4">

                    <div class="row">
                        <div class="col-6">
                            <img src="~/Images/logo-removebg-preview.png" width="90px" style="padding-top: 25px;" />
                        </div>
                    </div>
                </div>
                <div class="col-md-4" style="color:gold">
                    <h5 class="text-md-right" style="padding-top: 50px" ">© BOBATEA. All rights reserved.</h5>

                </div>
                <div class="col-md-4" style="padding: 50px;">
                    <a href="" class="item-link" style=" padding: 20px;font-size:30px;">

                        <i class="fa-brands fa-facebook"></i>
                    </a>
                    <a href="" class="item-link" style=" padding: 20px;font-size:30px;">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

demoweb/Views/Shared/_ProductLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/mystyle.css" />
    <link rel="stylesheet" href="~/Fonts/themify-icons/themify-icons.css" />
    <link href="~/Scripts/script.js" rel="stylesheet" />
    <script src="~/Scripts/JavaScriptlinedown.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/5026e71056.js" crossorigin="anonymous"></script>



</head>
<body>
    <div id="div-top">
        <ul id="nav">
            <li id="top-logo">
                <a href="/Home/TrangChu">
                    <img src="~/Images/logo-removebg-preview.png" alt="logo" class="logo" link />
                </a>



                @* <li>
                        <div class="wrap">
                            <form action="" class="search" method="post">
                                <input type="text" class="searchTerm" placeholder="Bạn muốn tìm gì?">
                                <button type="submit" class="searchButton">
                                    Submit
                                </button>
                            </form>
                        </div>
                    </li>*@
            <li>
                <div class="wrap">
                    <form action="" class="search" method="post">
                        @using (Html.BeginForm("ProductList", "Products", FormMethod.Get))
                        {
                            <table>
                                <tr>
                                    <td>
                                        <input class="input-search" name="SearchString" placeholder="Tìm sản phẩm..." />
                                    </td>
                                </tr>
                            </table>
                        }
                    </form>
                </div>
            </li>
        </ul>
        <ul class="nav2" style="float:right;display:flex">
            <div class="navlogin">
                <a class="ti-github">
                    @if (Session["TaiKhoan"] != null)
                    {
                        @Session["TaiKhoan"]

                    }
                </a>
                    <ul class="navlog"style=" padding: 20px;">
                        <li>
                            @if (Session["TaiKhoan"] != null)
                            {
                                <a href="/Users/Logout">
                                    Logout
                                </a>
                            }
                            else
                            {
                                <a href="#">
                                    Logout
                                </a>
                            }
                        </li>
                    </ul>                      
            </div>
            <li>
                <div class="search-btn">
                    @Html.Action("CartPartial", "Cart")
                </div>
            </li>

        </ul>



    </div>
    <div id="div-main">
        <div class="sidebar-left" style="height:100%;background-color:white;width:30%">
            <div class="list-card" style="height: 100%;width:100%">
                @{ Html.RenderAction("CategoryPartial", "Categories");}
            </div>
        </div>
        <div class="sidebar-right">
            @RenderBody()
        </div>

    </div>
    <footer class="footer" style="background-color: #333" ;>
        <div class="container">
            <div class="row">
                <div class="col-md-4">

                    <div class="row">
                        <div class="col-6">
                            <img src="~/Images/logo-removebg-preview.png" width="90px" style="padding-top: 25px;" />
                        </div>
                    </div>
                </div>
                <div class="col-md-4" style="color:gold">
                    <h5 class="text-md-right" style="padding-top: 50px" ">© BOBATEA. All rights reserved.</h5>

                </div>
                <div class="col-md-4" style="padding: 50px;">
                    <a href="" class="item-link" style=" padding: 20px;font-size:30px;">
                       
                        <i class="fa-brands fa-facebook"></i>
                    </a>
                    <a href="" class="item-link" style=" padding: 20px;font-size:30px;">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>